DROP TABLE IF EXISTS MESSAGES;
DROP TABLE IF EXISTS USERS;
  
CREATE TABLE MESSAGES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  sender VARCHAR(50) NOT NULL,
  recipient VARCHAR(50) NOT NULL,
  content VARCHAR(250) DEFAULT NULL
);

CREATE TABLE USERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  uuid VARCHAR(50) NOT NULL,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(250) NOT NULL,
  alias VARCHAR(10) NOT NULL
);

